language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0
env: MIX_ENV=test
sudo: false # faster builds
addons:
  postgresql: '9.4'
services:
  - postgresql
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix test
