language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0
env: MIX_ENV=test
sudo: false # faster builds
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix test
  - mix dogma
